# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_value', models.CharField(blank=True, max_length=15, verbose_name='What dosage did you take?')),
                ('dose_unit', models.CharField(blank=True, choices=[('', ''), ('CFU', 'CFU'), ('fl oz', 'fl oz'), ('g', 'g'), ('IU', 'IU'), ('ug', 'ug'), ('mg', 'mg'), ('mL', 'mL'), ('oz', 'oz'), ('Tbsp', 'Tbsp'), ('tsp', 'tsp')], default='', max_length=5, verbose_name='Dosage unit')),
                ('dose_frequency', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='How often was the dosage above taken?')),
                ('dose_frequency_unit', models.CharField(blank=True, choices=[('', ''), ('day', 'per day'), ('week', 'per week'), ('month', 'per month'), ('year', 'per year')], default='', max_length=9, verbose_name='Dosage frequency unit')),
                ('dose_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='How long did you take the product?')),
                ('dose_duration_unit', models.CharField(blank=True, choices=[('', ''), ('day', 'days'), ('week', 'weeks'), ('month', 'months'), ('year', 'years')], default='', max_length=5, verbose_name='Duration unit')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention', models.CharField(max_length=30, verbose_name='Name of Intervention')),
                ('brand', models.CharField(blank=True, max_length=30, verbose_name='Is this intervention associated with a particular brand?')),
                ('purpose', models.CharField(max_length=100, verbose_name='Purpose of Intervention')),
                ('details', models.CharField(max_length=5000)),
                ('effectiveness', models.PositiveSmallIntegerField(verbose_name='Overall effectiveness')),
                ('slug', models.SlugField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experiences',
            },
        ),
        migrations.CreateModel(
            name='ExperienceSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_terms', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experiences.Experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(blank=True, max_length=20, verbose_name='What symptoms were you addressing?')),
                ('pre_intervention', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='before')),
                ('post_intervention', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='after')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='Experiences.Experience')),
            ],
        ),
        migrations.AddField(
            model_name='dose',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='Experiences.Experience'),
        ),
    ]
